# Utilise une image de base officielle de Node.js
FROM node:18

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copie les fichiers package.json et package-lock.json
COPY package*.json ./

# Installe les dépendances du projet
RUN npm install

# Copie le reste des fichiers du projet
COPY . .

# Expose le port sur lequel l'application s'exécute
EXPOSE 3000

# Commande pour démarrer l'application
CMD ["npm", "start"]


# Pour construire l'image Docker, exécutez la commande suivante dans le répertoire du projet :
# docker build -t node-app .
# -t node-app : nom de l'image
# . : répertoire courant
# Pour exécuter l'image Docker, exécutez la commande suivante :
# docker run -p 3000:3000 node-app
# -p 3000:3000 : mappage du port 3000 du conteneur sur le port 3000 de l'hôte

# docker ps : liste les conteneurs en cours d'exécution

# un docker file permet de créer une image docker
# un docker image est une image de base qui contient un système d'exploitation et des logiciels installés
# cela permet de créer un environnement personalisé pour exécuter des applications
# on peut l'utiliser dans un fichier docker-compose.yml pour définir l'image d'un service à utiliser à la place d'une image de base (docker hub)
# un docker container est une instance d'une image docker
